# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.CharField(blank=True, max_length=30, null=True)),
                ('raw_text', models.CharField(blank=True, max_length=500, null=True)),
                ('gmail_id', models.CharField(blank=True, max_length=30, null=True)),
                ('telegram_message_id', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pollers.Card')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pollers.Category')),
            ],
        ),
    ]
